### PR TITLE
Supervision dataset integration

### PR DESCRIPTION
**Pull request by hardikdava**
This PR is for initial support for Object Detection Dataset #31.

Initial goal is to use `sv.DetectionDataset.from_yolo` instead of `ultralytics.Dataset`.

### CODE REVIEW

**Comment by hardikdava** [comment]
@AyushExel I will let you know once it is ready.

**Comment by hardikdava** [comment]
hey @AyushExel 👋 , I have currently implemented wrapper for `supervision` dataset which can further be extended for classification and segmentation as well. Let me know if it needed any changes.

**Comment by AyushExel** [comment]
@hardikdava thanks I'll take a look tomorrow morning. 
Does this integration mean that I can now load coco datasets as well?

**Comment by hardikdava** [comment]
@AyushExel currently, it works with yolo format but with single line of change, it can works with pascal voc and Coco without any issue.

**Comment by AyushExel** [comment]
Okay sounds good. I'd love to add support for coco datasets next!
Please mark this ready for review once you're done. Thanks!

**Comment by hardikdava** [comment]
@AyushExel let's finish this first and then we can move ahead with pascal voc and coco format. It will require some architecture issue to address first.

**Comment by AyushExel** [comment]
Sounds good! I'll just take a quick glance tomorrow morning and merge this! Thanks again for the effort

**Comment by AyushExel** [comment]
Screenshot 2023-08-24 at 12 13 38 PM
Hey I'm seeing this when building embeddings for VOC dataset. Doesn't happen in the main branch. Can you take a look?

**Comment by hardikdava** [comment]
@AyushExel can you update the code? I pushed updated code.

Here is my testing code.

```python

from yoloexplorer import Explorer

coco_exp = Explorer("coco128.yaml")

coco_exp.build_embeddings(force=True)

df = coco_exp.sql("SELECT * from 'table' WHERE labels like '%person%' and labels LIKE '%cat%'")

print(df)
coco_exp.plot_imgs(ids=df["id"][0:4].to_list())

```

Results:
```
2023-08-24 09:29:03.572 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2023-08-24 09:29:03.572 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2023-08-24 09:29:03.573 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2023-08-24 09:29:03.573 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
Ultralytics YOLOv8.0.120  Python-3.9.13 torch-2.0.1+cpu CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients
100%|██████████| 128/128 [00:12<00:00, 10.55it/s]
LanceDB: Embedding space built successfully.
   id  ...                                             vector
0  80  ...  [-0.13088425993919373, -0.09710405021905899, 0...

[1 rows x 6 columns]

Process finished with exit code 0

```

**Comment by AyushExel** [comment]
Yeah its working for coco128, but for VOC it's just showing this still 
Screenshot 2023-08-24 at 12 13 38 PM

**Comment by hardikdava** [comment]
@AyushExel Give me few minutes, I will add remaining parts for other formats. I thought our initial plan was first to add support yolo but using `supervision` and then do the same for others.

**Comment by AyushExel** [comment]
Ohh the VOC.yaml is in yolo format only.

**Comment by AyushExel** [comment]
> @AyushExel Give me few minutes, I will add remaining parts for other formats. I thought our initial plan was first to add support yolo but using `supervision` and then do the same for others.

Yeah only yolo format for now is fine. VOC.yaml is in yolo format only. please see this - https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/datasets/VOC.yaml
The embeddings start to build but after about 5K images the loop restarts and keep repeating

**Comment by hardikdava** [comment]
@AyushExel just a heads up. Currently, `supervision` is facing minor issue of lazy-loading but we are working on it.

**Comment by hardikdava** [comment]
@AyushExel FYI, this is going to be API used in future. Have a look here: https://supervision.roboflow.com/dataset/core/

**Comment by AyushExel** [comment]
> @AyushExel just a heads up. Currently, `supervision` is facing minor issue of lazy-loading but we are working on it. Can you first try with smaller dataset?

Yeah working with a smaller dataset but if it breaks with the larger one then we can't really use it as in most resources I've showcased VOC.

**Comment by AyushExel** [comment]
@hardikdava hey any update on this? Is large dataset handling in the roadmap for supervision sometime soon? Would love to get this in!

**Comment by hardikdava** [comment]
@AyushExel yes, we already have PR on this issue. I am a bit busy with my new job but I will update you asap!

**Comment by AyushExel** [comment]
Thanks! And congratulations on the new role

**Comment by hardikdava** [comment]
> Thanks! And congratulations on the new role

Thanks :) !

**Pull request closed without merging**
