### PR TITLE
Support multiple datasets

### PR DESCRIPTION
**Pull request by AyushExel**

### CODE REVIEW

**Comment by AyushExel** [comment]
Hey @onuralpszr pre-commit should be enabled right?

**Comment by AyushExel** [comment]
okay I don't think that's the case as black formatter didn't run

**Comment by onuralpszr** [comment]
> okay I don't think that's the case as black formatter didn't run

Yes it is just a import error from pytests but I was still saying "yes" to enable pre-commit.ci as well.

**Comment by AyushExel** [comment]
> Yes it is just a import error from pytests but I was still saying "yes" to enable pre-commit.ci as well.

I think we should set it in a way that it triggers on each PR automatically, before the CI tests run?

**Comment by AyushExel** [comment]
I'll attempt in this PR

**Comment by onuralpszr** [comment]
> > Yes it is just a import error from pytests but I was still saying "yes" to enable pre-commit.ci as well.
> 
> I think we should set it in a way that it triggers on each PR automatically, before the CI tests run?

You don't have to set anything as a "github action" just give permission to "pre-commit.ci" website it will come automatically.

**Comment by AyushExel** [comment]
Yeah I think it needs to be installed via marketplace and added to the repo automatically. I don't have the permission for that. I'll ask someone

**Comment by onuralpszr** [comment]
> Yeah I think it needs to be installed via marketplace and added to the repo automatically. I don't have the permission for that. I'll ask someone

Install from here : https://pre-commit.ci/

**Comment by AyushExel** [comment]
done

**Pull request merged**
