### PR TITLE
Add dashboard support

### PR DESCRIPTION
**Pull request by AyushExel**
@hardikdava  @onuralpszr this is how I want to implement it. the user can launch the dashboard by running `exp.dash`

```
exp = Explorer("coco128.yaml")
exp.build_embeddings()
exp.dash()
```

The cli launch script seems to be broken in some streamlit update. `streamlit.cli` moved to `streamlit.web.cli` but even on updating that it doesn't work so maybe the API has changed more than just the name. Can you guys think of another way to make this work?

### CODE REVIEW

**Comment by onuralpszr** [comment]
Minimal how to run via "python file" 


```python
import sys
import streamlit.web.cli as stcli

def run_streamlit_app():
    sys.argv = ["streamlit", "run", "dash.py"]
    stcli.main()

if __name__ == "__main__":
    run_streamlit_app()
```

This works fine and I also did some changes sending very soon too ( I just wanted to share info quicker )

**Comment by AyushExel** [comment]
Hmm.. would this work if I want to initialize the the state with the explorer object like I'm doing in this PR? 
I think when running thr file through subprocess the explorer object will be undefined, no ?

**Comment by onuralpszr** [comment]
> Hmm.. would this work if I want to initialize the the state with the explorer object like I'm doing in this PR? I think when running thr file through subprocess the explorer object will be undefined, no ?

That is what I am testing too. but should be "defined"

**Comment by AyushExel** [comment]
Okay 👍 let me know if it works for you

**Comment by onuralpszr** [comment]
> Hmm.. would this work if I want to initialize the the state with the explorer object like I'm doing in this PR? I think when running thr file through subprocess the explorer object will be undefined, no ?

I was able to run but you were right It does undefine keys, I need to either move or I need to pull some trick based on this 

https://docs.streamlit.io/library/get-started/multipage-apps  (If you okay with it) 

I will have multiple app run but just one page

**Comment by hardikdava** [comment]
@onuralpszr did you get it working?

**Comment by onuralpszr** [comment]
> @onuralpszr did you get it working?

UI yes but I need keys and datas

**Comment by AyushExel** [comment]
> > Hmm.. would this work if I want to initialize the the state with the explorer object like I'm doing in this PR? I think when running thr file through subprocess the explorer object will be undefined, no ?
> 
> I was able to run but you were right It does undefine keys, I need to either move or I need to pull some trick based on this
> 
> https://docs.streamlit.io/library/get-started/multipage-apps (If you okay with it)
> 
> I will have multiple app run but just one page

As long as it doesn't interfere with user directly, I think it should be fine. Let's just get it working and then try to refine it..

**Comment by AyushExel** [comment]
This is also why I was a bit skeptical about using dashboards. Maybe in the long run the best thing would be to build our own dashboard from scratch using react/js

**Comment by hardikdava** [comment]
@AyushExel should we continue working on dashboard or some other issue?

**Comment by AyushExel** [comment]
It really depends on whether it works. @onuralpszr is trying to get it working. If it works we can continue with it for a while.

**Comment by hardikdava** [comment]
@AyushExel Why don't we initialize state in runtime? In that way, we can use same app for another session. User does not have stop and restart session. What do you think?

```bash
start dash without explorer
allow user to chose required option to initialize `explorer`
DO FURTHER
```

**Comment by hardikdava** [comment]
@AyushExel @onuralpszr It is natural that you can not pass state objects without creating app. I analyzed the code from `dash` branch. Technically you can not pass state object across many apps. First you have to initialize the app and later you can set `explorer` object using other methods like callback, etc. But that is not the case currently.

**Comment by onuralpszr** [comment]
> @AyushExel @onuralpszr It is natural that you can not pass state objects without creating app. I analyzed the code from `dash` branch. Technically you can not pass state object across many apps. First you have to initialize the app and later you can set `explorer` object using other methods like callback, etc. But that is not the case currently.

I was already aware that but problem is "not" what you said.  Problem is when we use "cli" tricks I had to create new "process" which means "ANYTHING" we create in current process will be not accessible. So for that reason I am trying to change that behaviour via creating multi page or if it is too hacky, I am also considering to change to something else as well.

**Comment by onuralpszr** [comment]
> @AyushExel Why don't we initialize state in runtime? In that way, we can use same app for another session. User does not have stop and restart session. What do you think?
> 
> ```shell
> start dash without explorer
> allow user to chose required option to initialize `explorer`
> DO FURTHER
> ```

We do that too but same reason what I wrote above also cancel that variable too

**Comment by hardikdava** [comment]
> > @AyushExel Why don't we initialize state in runtime? In that way, we can use same app for another session. User does not have stop and restart session. What do you think?
> > ```shell
> > start dash without explorer
> > allow user to chose required option to initialize `explorer`
> > DO FURTHER
> > ```
> 
> We do that too but same reason what I wrote above also cancel that variable too
@AyushExel @onuralpszr 
First thing we need to make clear that we can not make instance of `Explorer` then pass it to streamlit app, unless we use any inmemory database that we do not want. So solution is that we start streamlit app then create `exp =Explorer()` To get all the args, I suggest following solution.


Solution-1 (Not recommended):
save all args required to make `exp =Explorer() ` as environmental variable.

Solution-2:
save all args required to make `exp =Explorer() ` in a temporary file and read all data from there when we create an instance of `Explorer`

**Comment by AyushExel** [comment]
Not sure. I'd prefer to keep the experience intuitive. Maybe there's a way, I'm not sure. 
@hardikdava can you implement solution 2 and make a PR on this branch. 
Meanwhile I'll try to explore plotly dash and react material ui

**Comment by AyushExel** [comment]
@onuralpszr @hardikdava okay guys if this blocker isn't resolved, I think the way forward would be to build a js dashboard form scratch :(

**Comment by onuralpszr** [comment]
> @onuralpszr @hardikdava okay guys if this blocker isn't resolved, I think the way forward would be to build a js dashboard form scratch :( 

I had a irl (workday) i will look before close but if you want to go js/ts sure

**Comment by AyushExel** [comment]
@onuralpszr ohh okay. Let me know if you make some progress. I'm also trying something hacky, but if I can't get it working before going to bed, I'll probably try js from tomorrow

**Comment by onuralpszr** [comment]
Consider gradio and others before go js we have other good options too

**Comment by AyushExel** [comment]
Gradio might have the same problem related to state management. It's for simple input - output experiences I'd say not multi stage apps. But yes plotly dash might be an alternative..

**Comment by AyushExel** [comment]
@onuralpszr @hardikdava ok guys, I think I made some progress. Now the problem is that streamlit accepts custom cmd line args like this `-- --` but for some reason when invoking it like you mentioned @onuralpszr it doesn't doesn't accept that..
```
Error: No such option: -- --info
```
I think if this issue is solved we'll have a working solution

**Comment by hardikdava** [comment]
@AyushExel I just tested the update. It is throwing the error you mentioned about `info`.

**Comment by AyushExel** [comment]
YOOO GUYSSS!!!!!!

Screenshot 2023-07-14 at 11 48 23 PM

**Comment by onuralpszr** [comment]
Awesome

**Comment by hardikdava** [comment]
> YOOO GUYSSS!!! EDIT: nvm I ran through cmdline :)
> Screenshot 2023-07-14 at 11 48 23 PM

Can you tell me how you run it?

**Comment by AyushExel** [comment]
Ohh I actually ran through commandline and didn't notice.. basically the problem is the same:
The same command runs properly in cmdline 
```
def launch(info):
    cmd = ["streamlit", "run", __file__, "-- --info", str(info.name)]
    try:
        subprocess.run(cmd, check=True)
    except Exception as e:
        print(e)
```
but complains that "-- --info is not a valid argument when running from pytohn"

**Comment by hardikdava** [comment]
@AyushExel Just tested it and seems fine. I do not have any idea of writing tests for streamlit.

**Comment by AyushExel** [comment]
hey @onuralpszr @hardikdava i think this is good now, but it'll be useless if we can't select multiple images at once. i saw that someone made the PR to enable this in the plugin but the author hasn't accepted it. Do you guys know how to use unpublished streamlit plugins directly in the repo? https://github.com/jrieke/streamlit-image-select/pull/11

**Comment by hardikdava** [comment]
@AyushExel it's pip installation. There are several plugins like this.

**Comment by onuralpszr** [comment]
For pip use this format in here 

https://stackoverflow.com/a/20101940

**Comment by AyushExel** [comment]
ohh i'm confused because of this part https://github.com/jrieke/streamlit-image-select/blob/main/streamlit_image_select/__init__.py#L15
It seems like installing from the source will hardcode the port. I'll try it.. but I guess we might need to publish the plugin to make it work seamlessly with Streamlit. Not sure though as its streamlit

**Comment by AyushExel** [comment]
Screenshot 2023-07-15 at 9 28 06 PM
yeah, doesn't work on pip installation

**Comment by hardikdava** [comment]
@AyushExel See [here](https://github.com/jrieke/streamlit-image-select/tree/main) external component is pip installable but not every components.

**Comment by AyushExel** [comment]
yeah that is pip installable because it is published. the branch is not published, and installing it from source doesn't work

**Comment by AyushExel** [comment]
@onuralpszr have you ever published a package using poetry as mentioned in the ^^ above repo branch?
I tried changing the name of the repo and publishing it but Poetry tells me that the folder is not found. I guess this is different from using twine to publish

**Comment by onuralpszr** [comment]
@AyushExel  i did publish poetry packages before many times. I think you may be miss some sort of config, how is your folder looks like and how is your toml file looks like  ?

**Comment by AyushExel** [comment]
@onuralpszr I'm trying to publish this repo. Here's what I've changed:
* folder name from `streamlit-image-select` to `streamlit-dash`
* Updated the toml file like this
Screenshot 2023-07-15 at 10 17 44 PM
And then following the steps to build.

**Comment by onuralpszr** [comment]
What about the folder next to toml is it same too  ?

**Comment by AyushExel** [comment]
Screenshot 2023-07-15 at 10 35 10 PM
Folder next to toml like this right?

**Comment by AyushExel** [comment]
@onuralpszr @hardikdava If either of you could publish this branch on pypi under any name, it'd be very helpful. I've tried many times but I'm not able to run `poetry build` succussfully even without changing anything.

**Comment by onuralpszr** [comment]
I will do it

**Comment by AyushExel** [comment]
Thanks 🙏

**Comment by AyushExel** [comment]
> I will do it

Ohh by this branch I mean https://github.com/the-beee/streamlit-image-select/tree/main

**Comment by AyushExel** [comment]
Any luck?

**Comment by onuralpszr** [comment]
> Any luck?

https://github.com/onuralpszr/streamlit-dash/actions/runs/5567474740 

Just fixing webpack nodejs and then I am done I was able to run smoothly

**Comment by onuralpszr** [comment]
> Any luck?

This project npm/nodejs side require 

> Any luck?

Upload complete : https://pypi.org/project/streamlit-dash/.  (doing last tests)

**Comment by onuralpszr** [comment]
> Any luck?

image

**Comment by onuralpszr** [comment]
image

**Comment by onuralpszr** [comment]
```
[]
[]
['images/cat1.jpeg']
['images/cat1.jpeg', 'https://bagongkia.github.io/react-image-picker/0759b6e526e3c6d72569894e58329d89.jpg']
['images/cat1.jpeg', 'https://bagongkia.github.io/react-image-picker/0759b6e526e3c6d72569894e58329d89.jpg', <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=130x200 at 0x138CD3310>]
[]
[]
['images/cat1.jpeg']
[]
['https://bagongkia.github.io/react-image-picker/0759b6e526e3c6d72569894e58329d89.jpg']
['images/cat1.jpeg', 'https://bagongkia.github.io/react-image-picker/0759b6e526e3c6d72569894e58329d89.jpg']
[]
[]
['images/cat1.jpeg', 'https://bagongkia.github.io/react-image-picker/0759b6e526e3c6d72569894e58329d89.jpg', <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=130x200 at 0x138CD3D30>]
['images/cat1.jpeg', 'https://bagongkia.github.io/react-image-picker/0759b6e526e3c6d72569894e58329d89.jpg', <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=130x200 at 0x138BC9390>, array([[[252, 249, 244],
        [252, 249, 242],
        [253, 248, 242],
        ...,
        [ 96,  91,  85],
        [ 98,  93,  87],
        [ 99,  94,  88]],

       [[252, 249, 244],
        [252, 249, 242],
        [253, 248, 242],
        ...,
        [ 97,  92,  86],
        [ 99,  94,  88],
        [100,  95,  89]],

       [[253, 248, 244],
        [253, 248, 242],
        [253, 248, 242],
        ...,
        [ 98,  93,  87],
        [ 99,  94,  88],
        [100,  95,  89]],

       ...,

       [[156, 135,  92],
        [164, 143, 100],
        [169, 148, 105],
        ...,
        [ 97,  94,  89],
        [ 97,  94,  89],
        [ 96,  93,  88]],

       [[159, 138,  95],
        [165, 144, 101],
        [168, 147, 104],
        ...,
        [ 97,  94,  89],
        [ 97,  94,  89],
        [ 96,  93,  88]],

       [[162, 141,  98],
        [166, 145, 102],
        [166, 145, 102],
        ...,
        [ 96,  93,  88],
        [ 96,  93,  88],
        [ 96,  93,  88]]], dtype=uint8)]
```

**Comment by onuralpszr** [comment]
@AyushExel 

https://pypi.org/project/streamlit-dash/

For demo test 

https://github.com/onuralpszr/streamlit-dash/blob/main/demo/streamlit_app.py

I change lib name so be aware that too.

**Comment by AyushExel** [comment]
Perfect. I'll try it in an hour

**Comment by onuralpszr** [comment]
> Perfect. I'll try it in an hour

Awesome let me know how is it go.

**Comment by onuralpszr** [comment]
@AyushExel  I guess it works ? (since you sent a push ? )

**Comment by AyushExel** [comment]
Oh yeahh. I was building other things on top of it like query and search.. that is also done

**Comment by onuralpszr** [comment]
> Oh yeahh. I was building other things on top of it like query and search.. that is also done

Awesome :) I am glad it work but we gonna replace once they merge right ?

**Comment by onuralpszr** [comment]
> @onuralpszr nah I think let's keep developing our version and add new features when needed. We can't reply on folks merging changes forever

okay I am breaking fork and change name and readme too

**Pull request merged**
