### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by hardikdava**
This PR is regarding creating dashboard as per #12 .

**Requirement:**

- Easy to understand, use and modify
- Stateful app
- Scalable for adding more details

**Start Dashboard:**
dash

### CODE REVIEW

**Comment by hardikdava** [comment]
@AyushExel a small suggestion, we can use `supervision` for generated annotated images. It is very easy to use and with MIT License.

**Comment by AyushExel** [comment]
Oh the repo already generates annotated imgs. Are you seeing otherwise?

**Comment by AyushExel** [comment]
@hardikdava is this done or will you add more files? I see the dashboard.py file is empty..
To emulate the real world case, it would be best if you could create a dashboard that displays 50imgs(you use the same img 50times) as a grid that is scrollable. Then later I'll update that to display images form the dataset. How does that sound?

**Comment by hardikdava** [comment]
@AyushExel Give me few minutes. I am almost finish building sample visualization part.

**Comment by AyushExel** [comment]
Okay merging this in and I'll work on it some more in the main branch. Is there a way to launch this via python rather than terminal? 
I'd prefer for this to start automatically when user call plot_something()..

**Comment by hardikdava** [comment]
Yeah, it's possible. I will take a look at it tomorrow and update you.

**Comment by onuralpszr** [comment]
> Okay merging this in and I'll work on it some more in the main branch. Is there a way to launch this via python rather than terminal? 
> I'd prefer for this to start automatically when user call plot_something()..

I was following here and tldr answer is yes by using streamlit.cli and here is example gist (gist is not mine) 
 https://gist.github.com/nmichlo/75c07b512f635cc7bf013642af21b6ba

**Comment by AyushExel** [comment]
@onuralpszr thanks! Please feel free to add issues and ideas if you have any :)

**Comment by onuralpszr** [comment]
> @onuralpszr thanks! Please feel free to add issues and ideas if you have any :) 

You are welcome, i do have some already and going to open pr as well.

**Comment by hardikdava** [comment]
@AyushExel Please create issues of your ideas. so we can help you to grow more and make this repository more useful to community.

**Comment by AyushExel** [comment]
Appreciate it guys! I'll open issues. I've also added ideas in coming soon section:)

**Comment by AyushExel** [comment]
> > Okay merging this in and I'll work on it some more in the main branch. Is there a way to launch this via python rather than terminal?
> > I'd prefer for this to start automatically when user call plot_something()..
> 
> I was following here and tldr answer is yes by using streamlit.cli and here is example gist (gist is not mine) https://gist.github.com/nmichlo/75c07b512f635cc7bf013642af21b6ba

Not working :( I think the streamlit API changed

**Pull request merged**
